### ISSUE TITLE
Fixing lack of  UAC_RunElevated when $installMode == "all" on Windows

### ISSUE THREAD

**Issue by lidel** [lidel/electron-updater-altschmerz#1]
Ok, I believe custom NSIS macro fixed https://github.com/ipfs-shipyard/ipfs-desktop/pull/1679#issuecomment-705569228, but would appreciate a quick test @rafaelramalho19

1. Download  https://github.com/lidel/electron-updater-altschmerz/releases/download/v0.0.5/altschmerz-Setup-0.0.5.exe 
2. **Install it on Windows for all users** like here:
   > ![](https://user-images.githubusercontent.com/157609/95464730-95463b00-097a-11eb-92ab-6a58135baf33.PNG)
3. Run the app, it will open the window saying that the version is v0.0.5, keep it open
4. Wait for it to display a popup saying update to 0.0.6 was downloaded and will install it after the app quits
5. Close the window
6. You should see UAC window asking you allow the app to run as admin (_this step was missing_, and we want you to say yes here)
7. Wait a few seconds, the update will be applied silently in the background
8. Start the `altschmerz` again (via the start menu)
9. You should see Version v0.0.6

**Comment by rafaelramalho19** [comment]
It works on my machine.
